import { useState } from 'react';
import api from '../../services/api';

export default function StudentCheckIn() {
  const [tokenInput, setTokenInput] = useState('');
  const [loading, setLoading] = useState(false);
  const [errorMsg, setErrorMsg] = useState('');
  const [successMsg, setSuccessMsg] = useState('');

  const handleCheckIn = async (e) => {
    e.preventDefault();
    if (!tokenInput.trim()) {
      setErrorMsg('Please enter a valid attendance QR token.');
      return;
    }

    setErrorMsg('');
    setSuccessMsg('');
    setLoading(true);

    try {
      const res = await api.post('/api/attendance/check-in', {
        qrCodeToken: tokenInput.trim().toUpperCase()
      });

      if (res.data && res.data.success) {
        setSuccessMsg('Check-In Successful! Attendance marked as Present.');
        setTokenInput('');
      }
    } catch (err) {
      console.error('Check-in error:', err);
      setErrorMsg(err.response?.data?.message || 'Check-in failed. Invalid, expired, or unauthorized token.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column', gap: '30px', maxWidth: '600px', margin: '0 auto' }}>
      <div style={{ textAlign: 'center' }}>
        <h3 className="text-gradient" style={{ fontSize: '1.6rem', marginBottom: '8px' }}>
          Class QR Check-In
        </h3>
        <p className="text-secondary" style={{ fontSize: '0.9rem' }}>
          Scan or submit active attendance tokens generated by your instructors.
        </p>
      </div>

      {/* Viewfinder Mockup Card */}
      <div className="glass-panel" style={{
        padding: '40px 30px',
        display: 'flex',
        flexDirection: 'column',
        alignItems: 'center',
        gap: '30px',
        position: 'relative',
        overflow: 'hidden'
      }}>
        {/* Animated Neon Scanning Viewfinder Frame */}
        <div style={{
          width: '200px',
          height: '200px',
          border: '2px dashed rgba(139, 92, 246, 0.4)',
          borderRadius: 'var(--radius-lg)',
          position: 'relative',
          display: 'flex',
          alignItems: 'center',
          justifyContent: 'center',
          background: 'rgba(139, 92, 246, 0.02)',
          boxShadow: 'inset 0 0 20px rgba(139, 92, 246, 0.05)'
        }}>
          {/* Scanning Line Animation */}
          <div style={{
            position: 'absolute',
            width: '100%',
            height: '2px',
            background: 'linear-gradient(to right, transparent, hsl(var(--color-primary-hover)), transparent)',
            top: '0',
            animation: 'scanLine 3s linear infinite',
            boxShadow: '0 0 8px hsl(var(--color-primary-hover))'
          }}></div>
          
          <span className="text-muted" style={{ fontSize: '0.8rem', fontWeight: 'bold' }}>CAMERA SIMULATOR</span>
        </div>

        {/* Form and alerts */}
        <form onSubmit={handleCheckIn} style={{ width: '100%', display: 'flex', flexDirection: 'column', gap: '20px' }}>
          <div className="form-group" style={{ margin: 0 }}>
            <label className="form-label" style={{ textAlign: 'center' }}>Enter Attendance Code</label>
            <input
              type="text"
              className="form-input"
              style={{ textAlign: 'center', fontSize: '1.2rem', fontWeight: 'bold', fontFamily: 'monospace', letterSpacing: '2px' }}
              placeholder="e.g. QR_XXXXXX"
              value={tokenInput}
              onChange={(e) => setTokenInput(e.target.value)}
              disabled={loading}
              required
            />
          </div>

          <button
            type="submit"
            className="btn-primary"
            style={{ width: '100%', padding: '12px' }}
            disabled={loading}
          >
            {loading ? 'Submitting Check-In...' : 'Log Attendance'}
          </button>
        </form>

        {/* Notifications */}
        {errorMsg && (
          <span className="badge badge-danger" style={{ display: 'block', width: '100%', padding: '12px', textAlign: 'center', animation: 'fadeIn 0.2s forwards' }}>
            {errorMsg}
          </span>
        )}
        {successMsg && (
          <span className="badge badge-success" style={{ display: 'block', width: '100%', padding: '12px', textAlign: 'center', animation: 'fadeIn 0.2s forwards' }}>
            {successMsg}
          </span>
        )}
      </div>

      {/* Scanner inline CSS animations */}
      <style>{`
        @keyframes scanLine {
          0% { top: 0%; opacity: 0; }
          10% { opacity: 1; }
          90% { opacity: 1; }
          100% { top: 100%; opacity: 0; }
        }
      `}</style>
    </div>
  );
}
